"""Command-based processors for WSI analysis pipeline."""

from ..common import _get as _get
from ..common import _get_cluster_color as _get_cluster_color
from ..common import _progress as _progress
from .cache import CacheCommand as CacheCommand
from .cache import CacheResult as CacheResult
from .cache import Wsi2HDF5Command as Wsi2HDF5Command
from .cache import Wsi2HDF5Result as Wsi2HDF5Result
from .clustering import ClusteringCommand as ClusteringCommand
from .dzi import DziCommand as DziCommand
from .feature_extraction import FeatureExtractionCommand as FeatureExtractionCommand
from .pca import PCACommand as PCACommand
from .preview import BasePreviewCommand as BasePreviewCommand
from .preview import PreviewClustersCommand as PreviewClustersCommand
from .preview import PreviewLatentClusterCommand as PreviewLatentClusterCommand
from .preview import PreviewLatentPCACommand as PreviewLatentPCACommand
from .preview import PreviewScoresCommand as PreviewScoresCommand
from .show import ShowCommand as ShowCommand
from .umap_embedding import UmapCommand as UmapCommand
